### ISSUE TITLE
CTD from Piglin Brute charge

### ISSUE THREAD

**Issue by emerl66** [seymourimadeit/Piglin-Proliferation#34] opened 2024-09-30 10:04 UTC
When attacking the brute while the his shield bash dash animation is going will cause an immediate crash. Takes several attempts to relaunch to get back into the world or needing to disable then re-enable the mod to load the world save back up again.

**Comment by emerl66** [comment] 2024-09-30 12:37
After revisiting another spawner with piglin brutes that have the shields, the use of the charge attack just seems to cause my game to crash. The fix is still the same, having to disable the mod seems to prevent the issue from happening entirely.

**Comment by seymourimadeit** [comment] 2024-09-30 13:39
Dupe of #32 

Could you try the .jar from the .zip file I sent in that thread btw? It may contain a fix for it (and please send your crash report too!)

**Closed by seymourimadeit** 2024-09-30 13:39 UTC
